{
 "title": "SafeDomoticHome",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Motion sensor zone #1",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  isMagnetOn\nFROM motionz1\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Last 5 alarms event",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp AS \"time\",\nzone\nFROM alarmList\nORDER BY timestamp DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Motion sensor zone #0",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  isMagnetOn\nFROM motionz0\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Temperature over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "SELECT timestamp AS time, celsiusDegree AS data\nFROM thermometer\nORDER BY timestamp;"
    }
   ]
  },
  {
   "title": "Alarm Station (last 5 actions)",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\ntimestamp AS \"time\",\nCONCAT(IF(zone0 = 0,\"Zone 0: DISARMED |\",\"Zone 0: ARMED |\"),IF(zone1 = 0,\" Zone 1: DISARMED\",\" Zone 1: ARMED\")) AS action\nFROM alarmCmdLog\nORDER BY timestamp DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Smoke % over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  smokePercentage\nFROM vocMeter\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}